---
title: "fill gaps in RKI data"
output:
    html_document:
        toc: true
        toc_float: true
        theme: cosmo
        highlight: tango
---

# Loading the dataset

```{r load_data, echo=FALSE}
library(dplyr, warn.conflicts=FALSE)
library(tidyr)
library(lubridate, warn.conflicts=FALSE)
library(readr)

df = read.csv("RKI_COVID19_Dresden.csv")
levels(df$Altersgruppe)
head(df %>% filter(Altersgruppe == "A60-A79"))

df$Meldedatum = ymd_hms(df$Meldedatum)
df$Meldedatum_Epoch_days = as.numeric(df$Meldedatum)
df$Meldedatum_Epoch = as.numeric(as.POSIXct(df$Meldedatum,origin="1970-01-01",tz="CET"))

df$Datenstand = dmy_hm(df$Datenstand)

glimpse(df %>% filter(Altersgruppe == "A60-A79"))

```

# fill the gaps

```{r summ_data, echo=FALSE}

cat("Sum of all cases listed by RKI:",sum(df$AnzahlFall))

minepoch = min(df$Meldedatum_Epoch)
maxepoch = max(df$Meldedatum_Epoch)

mindays = min(df$Meldedatum_Epoch_days)
mindt = as_datetime(minepoch)
maxdays = max(df$Meldedatum_Epoch_days)

cat("earliest case:", as.character(as_datetime(minepoch)), mindays, as.character(mindt))

cat("most recent case:", as.character(as_datetime(max(df$Meldedatum_Epoch))),maxdays)

df$Meldedatum_Epoch_days_rel = as.double(df$Meldedatum - mindt) / (24*3600)

head(df$Meldedatum_Epoch_days_rel)

cumdf = df %>% 
arrange(Meldedatum_Epoch_days_rel) %>% 
mutate(laufendeSumme = cumsum(AnzahlFall)) %>%
select(Meldedatum_Epoch_days_rel,laufendeSumme,AnzahlFall)

print(cumdf)
sum(cumdf$AnzahlFall)
```

# reference test

```{r test}
df <- data.frame(id = rep(1:3, each = 5),
                 hour = rep(1:5, 3),
                 day = sample(15:29),
                 value = sample(1:15))
df

print("group_by(day)")
df %>% group_by(day) %>% mutate(csum = cumsum(value))

print("arrange(day)")
df %>% arrange(day) %>% mutate(csum = cumsum(value))

print("group_by(id)")
df %>% group_by(id) %>% mutate(csum = cumsum(value))

```
